/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int cost(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int cost_alloc_mem(void);
int cost_init_mem(int mem);
void cost_free_mem(int mem);
int cost_checkout(void);
void cost_release(int mem);
void cost_incref(void);
void cost_decref(void);
casadi_int cost_n_in(void);
casadi_int cost_n_out(void);
casadi_real cost_default_in(casadi_int i);
const char* cost_name_in(casadi_int i);
const char* cost_name_out(casadi_int i);
const casadi_int* cost_sparsity_in(casadi_int i);
const casadi_int* cost_sparsity_out(casadi_int i);
int cost_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int cost_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define cost_SZ_ARG 5
#define cost_SZ_RES 2
#define cost_SZ_IW 0
#define cost_SZ_W 1003002
#ifdef __cplusplus
} /* extern "C" */
#endif
