/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) my_function_delta_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[7] = {1, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[6] = {1, 2, 0, 1, 1, 0};
static const casadi_int casadi_s3[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s4[2] = {0, 1};
static const casadi_int casadi_s5[8] = {2, 2, 0, 2, 3, 0, 1, 1};
static const casadi_int casadi_s6[8] = {2, 2, 0, 1, 3, 0, 0, 1};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};

static const casadi_real casadi_c0[4] = {1., 0., 0., 1.};

/* delta_x:(Q[2x2],c[2],x[2],xd[2])->(delta[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+2, *w1=w+4, *w2=w+8, w3, *w4=w+13, w5, *w6=w+16, *w7=w+20, *w8=w+22, *w9=w+26, *w10=w+30, *w11=w+32;
  /* #0: @0 = zeros(2x1) */
  casadi_clear(w0, 2);
  /* #1: @1 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c0, 4, w1);
  /* #2: @2 = zeros(2x2) */
  casadi_clear(w2, 4);
  /* #3: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #4: @4 = zeros(1x2) */
  casadi_clear(w4, 2);
  /* #5: @5 = ones(1x2,1nz) */
  w5 = 1.;
  /* #6: @6 = input[0][0] */
  casadi_copy(arg[0], 4, w6);
  /* #7: @4 = mac(@5,@6,@4) */
  casadi_mtimes((&w5), casadi_s2, w6, casadi_s1, w4, casadi_s0, w, 0);
  /* #8: @4 = @4' */
  /* #9: @4 = (@3*@4) */
  for (i=0, rr=w4, cs=w4; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #10: @7 = zeros(1x2) */
  casadi_clear(w7, 2);
  /* #11: @5 = all_0.5(1x2,1nz) */
  w5 = 5.0000000000000000e-01;
  /* #12: @8 = @6' */
  for (i=0, rr=w8, cs=w6; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #13: @7 = mac(@5,@8,@7) */
  casadi_mtimes((&w5), casadi_s2, w8, casadi_s1, w7, casadi_s0, w, 0);
  /* #14: @7 = @7' */
  /* #15: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #16: (@2[:4:2] = @4) */
  for (rr=w2+0, ss=w4; rr!=w2+4; rr+=2) *rr = *ss++;
  /* #17: @4 = zeros(1x2) */
  casadi_clear(w4, 2);
  /* #18: @5 = ones(1x2,1nz) */
  w5 = 1.;
  /* #19: @4 = mac(@5,@6,@4) */
  casadi_mtimes((&w5), casadi_s3, w6, casadi_s1, w4, casadi_s0, w, 0);
  /* #20: @4 = @4' */
  /* #21: @4 = (@3*@4) */
  for (i=0, rr=w4, cs=w4; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #22: @7 = zeros(1x2) */
  casadi_clear(w7, 2);
  /* #23: @5 = all_0.5(1x2,1nz) */
  w5 = 5.0000000000000000e-01;
  /* #24: @7 = mac(@5,@8,@7) */
  casadi_mtimes((&w5), casadi_s3, w8, casadi_s1, w7, casadi_s0, w, 0);
  /* #25: @7 = @7' */
  /* #26: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #27: (@2[1:5:2] = @4) */
  for (rr=w2+1, ss=w4; rr!=w2+5; rr+=2) *rr = *ss++;
  /* #28: @9 = @2' */
  for (i=0, rr=w9, cs=w2; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #29: @1 = (@9\@1) */
  rr = w1;
  ss = w9;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[3], r[3], beta[2], w[4];
    casadi_qr(casadi_s1, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s4, casadi_s4);
    casadi_qr_solve(rr, 2, 0, casadi_s5, v, casadi_s6, r, beta, casadi_s4, casadi_s4, w);
  }
  /* #30: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #31: @4 = input[1][0] */
  casadi_copy(arg[1], 2, w4);
  /* #32: @7 = zeros(1x2) */
  casadi_clear(w7, 2);
  /* #33: @10 = input[2][0] */
  casadi_copy(arg[2], 2, w10);
  /* #34: @11 = input[3][0] */
  casadi_copy(arg[3], 2, w11);
  /* #35: @10 = (@10-@11) */
  for (i=0, rr=w10, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #36: @11 = @10' */
  casadi_copy(w10, 2, w11);
  /* #37: @7 = mac(@11,@6,@7) */
  for (i=0, rr=w7; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w11+j, tt=w6+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #38: @7 = @7' */
  /* #39: @7 = (@3*@7) */
  for (i=0, rr=w7, cs=w7; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #40: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #41: @7 = zeros(1x2) */
  casadi_clear(w7, 2);
  /* #42: @10 = @10' */
  /* #43: @10 = (@3*@10) */
  for (i=0, rr=w10, cs=w10; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #44: @7 = mac(@10,@8,@7) */
  for (i=0, rr=w7; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w10+j, tt=w8+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #45: @7 = @7' */
  /* #46: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #47: @0 = mac(@1,@4,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w1+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #48: output[0][0] = @0 */
  casadi_copy(w0, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int delta_x(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int delta_x_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int delta_x_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void delta_x_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int delta_x_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void delta_x_release(int mem) {
}

CASADI_SYMBOL_EXPORT void delta_x_incref(void) {
}

CASADI_SYMBOL_EXPORT void delta_x_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int delta_x_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int delta_x_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real delta_x_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* delta_x_name_in(casadi_int i) {
  switch (i) {
    case 0: return "Q";
    case 1: return "c";
    case 2: return "x";
    case 3: return "xd";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* delta_x_name_out(casadi_int i) {
  switch (i) {
    case 0: return "delta";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* delta_x_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s7;
    case 2: return casadi_s7;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* delta_x_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int delta_x_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 34;
  return 0;
}

CASADI_SYMBOL_EXPORT int delta_x_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 34*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
